-- require("bjufre.themes.github")
require("bjufre.themes.tokyonight")
-- require("bjufre.themes.catppuccin")
-- require("bjufre.themes.kanagawa")
-- require("bjufre.themes.nord")
-- require("bjufre.themes.poimandres")
-- require("bjufre.themes.everforest")
-- require("bjufre.themes.rose-pine")
