-- require("bjufre.themes.catppuccin")
-- require("bjufre.themes.yugen")
require("bjufre.themes.poimandres")
-- require("bjufre.themes.nord")
-- require("bjufre.themes.rose-pine")
-- require("bjufre.themes.nordic")
